# Generated by Django 3.0.2 on 2020-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200309_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='body_points',
            field=models.IntegerField(choices=[(4, '过硬'), (3, '健康'), (2, '亚健康'), (1, '生病')], default=3, verbose_name='身体素质'),
        ),
        migrations.AlterField(
            model_name='user',
            name='match_points',
            field=models.FloatField(default=0.0, verbose_name='比赛成绩'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_points',
            field=models.IntegerField(choices=[(4, '积极'), (3, '一般'), (2, '很少'), (1, '排斥')], default=3, verbose_name='社团情况'),
        ),
        migrations.AlterField(
            model_name='user',
            name='test_points',
            field=models.FloatField(default=0.0, verbose_name='考试成绩'),
        ),
    ]
